/* Module 1: Assignment 2
Name:   Gabby Willard
Class:  SDEV 200
Date:   8/25/25
File:   M01_Assignment_2.java
*/

/* 6.31 (Financial: credit card number validation)
Credit card numbers follow certain patterns. A credit card number must have between 13 and 16 digits. It must start with
  • 4 for Visa cards
  • 5 for Master cards
  • 37 for American Express cards
  • 6 for Discover cards
In 1954, Hans Luhn of IBM proposed an algorithm for validating credit card numbers. The algorithm is useful to determine whether a credit card is scanned correctly by a scanner. Credit card numbers are generated by the following validity check, commonly known as the Luhn check or the Mod 10 check,which can be described as follows (for illustration, consider the card number 4388576018402626)

*/